"use strict";
//
// UTILITIES (3)
Object.defineProperty(exports, "__esModule", { value: true });
exports.IOccupations = exports.ICategories = exports.IReasons = exports.Imonths = exports.sourcesOfIncome = exports.smallNumbersMappings = void 0;
exports.smallNumbersMappings = [
    "periodx",
    "sensus",
    "fee_loan",
    "fee_instalment",
    "days_penalized",
    "wdelays",
    "periodYear",
    "salaryQueued",
    "fotox",
    "yearx",
    "year",
    "month",
    "worked",
    "receipts",
    "receipt",
    "depositx",
    "deals_open",
    "deals_active",
    "errors",
];
exports.sourcesOfIncome = [
    "Artist",
    "Business",
    "Consultant",
    "Director",
    "Dividends",
    "Doctor",
    "Employee",
    "Entrepreneur",
    "Freelancing",
    "Gardener",
    "Landlord",
    "Investment",
    "Maid",
    "Nurse",
    "Pension",
    "RealEstate",
    "Royalties",
    "Salary",
    "Salesperson",
    "Teacher",
    "Trader",
].sort();
exports.Imonths = [
    "01-January",
    "02-February",
    "03-March",
    "04-April",
    "05-May",
    "06-June",
    "07-July",
    "08-August",
    "09-September",
    "10-October",
    "11-November",
    "12-December",
];
exports.IReasons = [
    "Disbursement",
    "Transport",
    "NAPSA",
    "ZRA",
    'License',
    "Airtime",
    "Rentals",
    "Housing",
    "Salaries",
    "Hardware",
    "Others",
];
exports.ICategories = [
    "Transport",
    "NAPSA",
    "ZRA",
    "License",
    "Airtime",
    "Rentals",
    "Salaries",
    "Home-Visit",
    "Others",
];
exports.IOccupations = [
    "Accountant",
    "Agent",
    "Analyst",
    "Architect",
    "Artist",
    "Athlete",
    "Businessman",
    "Chef",
    "Civil Servant",
    "Clergy",
    "Collector",
    "Designer",
    "Doctor",
    "Driver",
    "Electrician",
    "Engineer",
    "Farmer",
    "Guard",
    "Journalist",
    "Lawyer",
    "Lecturer",
    "Manager",
    "Nurse",
    "Officer",
    "Pharmacist",
    "Politician",
    "Plumber",
    "Scientist",
    "Social Worker",
    "Teacher",
    "Unknown",
];
// ====================================================================================
